# modbus_energy_meter/config/registers.py

ESSENTIAL_REGISTERS = [
    "active_power",
    "input_power",
    "power_meter_active_power",
    "storage_charge_discharge_power",
    "storage_state_of_capacity",
    "daily_yield_energy",
    "accumulated_yield_energy",
    "grid_exported_energy",
    "grid_accumulated_energy",
    "storage_charge_capacity_today",
    "storage_discharge_capacity_today",

    "pv_01_voltage",
    "pv_01_current",
    "pv_02_voltage",
    "pv_02_current",
    "pv_03_voltage",
    "pv_03_current",
    "pv_04_voltage",
    "pv_04_current",

    "storage_total_charge",
    "storage_total_discharge",
    "storage_bus_voltage",
    "storage_bus_current",

    "grid_A_voltage",
    "grid_B_voltage",
    "grid_C_voltage",
    "line_voltage_A_B",
    "line_voltage_B_C",
    "line_voltage_C_A",
    "grid_frequency",
    "meter_status",
    "power_meter_reactive_power",

    "active_grid_A_current",
    "active_grid_B_current",
    "active_grid_C_current",
    "active_grid_A_B_voltage",
    "active_grid_B_C_voltage",
    "active_grid_C_A_voltage",
    "active_grid_A_power",
    "active_grid_B_power",
    "active_grid_C_power",
    "active_grid_frequency",
    "active_grid_power_factor",

    "internal_temperature",
    "day_active_power_peak",
    "power_factor",
    "efficiency",
    "reactive_power",
    "insulation_resistance",

    "device_status",
    "state_1",
    "state_2",

    "model_name",
    "serial_number",
    "rated_power",
    "startup_time",

    "storage_running_status",
    "alarm_1",
]
